name: uniconnect
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  timeago: ^3.4.0
  intl: ^0.18.1
  image_picker: ^0.8.7+5
  image_cropper: ^3.0.3
  fluttertoast: ^8.2.1
  firebase_storage: ^11.2.0
  flutter_image_slider: ^0.0.2
  flutter_svg: ^2.0.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  map_launcher: ^2.5.0+1
  uuid: ^3.0.7
  url_launcher: ^6.1.12



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/11668571_20943645.jpg
    - assets/images/UniConnect.png
    - assets/images/main_top.png
    - assets/images/main_bottom.png
    - assets/images/chat.png
    - assets/images/login.png
    - assets/images/signup_top.png

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
